spring:
    application:
        name: bshop42

    freemarker:
        template-loader-path: classpath:/templates
        suffix: .ftl

    datasource:
        url: jdbc:postgresql://localhost:5432/bshop42
        username: postgres
        password: password
        hikari:
            maximum-pool-size: 20

    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true

logging:
    level:
        com.zaxxer.hikari: DEBUG
